spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.242.0:3306/todos
    username: todos
    password: 1234
  web:
    resources:
      static-locations: "classpath:/build"
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      logic-delete-field: deleted
